version: "3.5"

networks:
  myvpn-net:
    name: myvpn-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8

services:
  vpn:
    container_name: vpn
    build: alpine-custom
    image: villcabo/ovpn-client
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_CONF:-/path/to/vpn.ovpn}:/conf.ovpn
    environment:
      OVPN_USERNAME: ${OVPN_USERNAME:-username}
      OVPN_PASSWORD: ${OVPN_PASSWORD:-password}
    networks:
      myvpn-net:
        ipv4_address: 10.0.0.13