name: vpnclient

networks:
  myvpn-net:
    name: myvpn-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8

services:
  vpn:
    container_name: vpn_sintesis
    build: alpine-custom
    image: villcabo/ovpn-client
    # restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      net.ipv4.ip_forward: 1
    dns:
      - 199.3.0.253
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_CONF:-/path/to/vpn.ovpn}:/root/vpn.ovpn
      # - ~/.ssh/config:/root/.ssh/config:ro
      # - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519
    environment:
      OVPN_USERNAME: ${OVPN_USERNAME:-username}
      OVPN_PASSWORD: ${OVPN_PASSWORD:-password}
      SHARED_IPS: ${SHARED_IPS}
    networks:
      myvpn-net:
        ipv4_address: 10.0.0.13
