name: openvpn-client

networks:
  vpn-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.55.11.0/28 # Use /28 for 16 IPs

services:
  vpn:
    container_name: openvpn-client
    build: ubuntu-custom
    image: villcabo/openvpn-client
    restart: unless-stopped
    networks:
      vpn-network:
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      net.ipv4.ip_forward: 1
    dns:
      - 199.3.0.253
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_CONF:-/path/to/vpn.ovpn}:/root/vpn.ovpn
    environment:
      OVPN_USERNAME: ${VPN_USERNAME}
      OVPN_PASSWORD: ${VPN_PASSWORD}
